### ISSUE TITLE
USI-LS compat, ModuleHabitation doesn't consume EC

### ISSUE THREAD

**Issue by MaximeBrean** [ChrisAdderley/StationPartsExpansionRedux#138]
Both `PPD-24 'Panorama' Observation Module` and `PXL-9 Astrogation Module` parts has no EC consumption for the ModuleHabitation.
The module configuration is handled by `StationPartsExpansionRedux\Patches\SSPXR-USILS.cfg` patch (l.106-128)

**Comment by ChrisAdderley** [comment]
Yeah I don't know what's going on there, I'll have a look.

**Comment by ChrisAdderley** [comment]
I suspect this has been addressed, but I will need confirmation

**Comment by MaximeBrean** [comment]
Sorry for the late reply.
It's still not fixed, but #203 will fix that.

**Comment by ChrisAdderley** [comment]
Thanks, will be in next update.

**Comment by MaximeBrean** [comment]
You're welcome !

**Comment by MaximeBrean** [comment]
closing the issue as the PR has been merged.
