### ISSUE TITLE
PPD-Series Flat Adapter collider issue

### ISSUE THREAD

**Issue by Sharpspoonful** [ChrisAdderley/StationPartsExpansionRedux#60]
![PPD-series adapter](https://user-images.githubusercontent.com/8024470/31303859-e998d09a-aac9-11e7-8732-cadfefbd2f65.png) This screenshot shows an issue I've found with the collider extending outside the model. While you can attach other parts in the VAB, docking ports cannot be placed on the node as the invisible colliders prevent docking in flight.

**Comment by ChrisAdderley** [comment]
This should have been resolved a few commits ago... check to make sure you pulled the latest version (I just pushed a new one to be sure).

**Comment by Sharpspoonful** [comment]
I double-checked that I pulled the 1.0.0 master, and redownloaded it. Still seeing objects that can surfaceAttach attaching to the invisible colliders.

**Comment by ChrisAdderley** [comment]
Oh... I thought that was the 1.25m part! Yeah there's a crapton of collider problems with the 2.5m parts! I'll resolve this one but don't expect any of them to be right until you see some kind of note that I've done a collider/polish pass on them.
